"""Added user.is_banned

Revision ID: bcb73ffa4c43
Revises: 36e96d71d2ef
Create Date: 2023-12-25 01:27:03.495288

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcb73ffa4c43"
down_revision: Union[str, None] = "36e96d71d2ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_banned", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_banned")
    # ### end Alembic commands ###
